services:
    secshare-app:
        image: secshare
        container_name: secshare
        restart: unless-stopped
        environment:
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=db
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - secshare
        depends_on:
            - db

    nginx:
        image: nginx:1.17-alpine
        container_name: secshare-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - secshare

    db:
        image: mysql:8.0
        container_name: secshare_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        networks:
            - secshare

networks:
    secshare:
        driver: bridge

volumes:
    dbdata:
        driver: local
