services:
    secshare-app:
        build:
            args:
                user: secshare
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: secshare
        container_name: secshare
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - secshare

    nginx:
        image: nginx:1.17-alpine
        container_name: secshare-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - secshare

    db:
        image: mysql:8.0
        container_name: secshare_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
#        volumes:
#            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - secshare

networks:
    secshare:
        driver: bridge

volumes:
    dbdata:
        driver: local
